CREATE TABLE Patient(
UserName		CHAR(10)	NOT NULL,	
UserPassword	CHAR(15) 	NOT NULL,
PRIMARY KEY(Username)
);

CREATE TABLE Diagnoses(
DiagnosisID		INT				NOT NULL	AUTO_INCREMENT,
UserName 		CHAR(15)		NOT NULL	REFERENCES Patient(UserName),
RawInput		VARCHAR(1000)	NOT NULL,
CorrectedInput	VARCHAR(1000)	DEFAULT NULL,
TimeEntered		TIMESTAMP		DEFAULT CURRENT_TIMESTAMP,
TiltX			DECIMAL(2,0)	DEFAULT NULL,
TiltY			DECIMAL(2,0)	DEFAULT NULL,
TiltZ			DECIMAL(2,0)	DEFAULT NULL,
Lat				DECIMAL(9,6)	DEFAULT NULL,
Long			DECIMAL(9,6)	DEFAULT NULL,
WavLoc			CHAR(25)		NOT NULL,
Probability		DECIMAL(6,5)	DEFAULT NULL,
GroundTruth		DECIMAL(1,0)	DEFAULT NULL,	
PRIMARY KEY(DiagnosisID)
);